### ISSUE TITLE
Audio recording is cut off under Firefox 87.0

### ISSUE THREAD

**Issue by A0B** [justinhunt/moodle-qtype_poodllrecording#8]
Environment:
Moodle 3.0.9 (Build: 20170313)
qtype_poodllrecording_version | 2020061600

Poodll Recording audio is set to unlimited time.
Under Firefox 87.0 when a student starts recording, PoodLL allows to record the needed time but the record length is cut to ~ 5 sec.
Under Chrome the record length is as expected.

**Comment by justinhunt** [comment]
Thanks Boris. I posted a fix for this in the Poodll Filter. Please update that to the latest version.
